apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: cluster-reader
rules:
    - apiGroups:
          - "*"
      resources:
          - componentstatuses
          - configmaps
          - endpoints
          - events
          - limitranges
          - namespaces
          - nodes
          - persistentvolumeclaims
          - persistentvolumes
          - pods
          - podtemplates
          - replicationcontrollers
          - resourcequotas
          - secrets
          - serviceaccounts
          - validatingwebhookconfigurations
          - customresourcedefinitions
          - apiservices
          - controllerrevisions
          - daemonsets
          - deployments
          - replicasets
          - statefulsets
          - horizontalpodautoscalers
          - healthstates
          - cronjobs
          - jobs
          - certificatesigningrequests
          - leases
          - endpointslices
          - ingresses
          - ingressclasses
          - ingresses
          - networkpolicies
          - runtimeclasses
          - poddisruptionbudgets
          - poddisruptionbudgets
          - clusterrolebindings
          - clusterroles
          - rolebindings
          - roles
          - priorityclasses
          - csidrivers
          - csinodes
          - storageclasses
          - volumeattachments
      verbs:
          - get
          - list
